[build]
command = ""
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
HUGO_VERSION       = "0.109.0"
NODE_VERSION       = "v18.12.1"
NPM_VERSION        = "8.19.2"

[context.split1]
command = ""

    [context.split1.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.109.0"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"

[context.deploy-preview]
command = ""

    [context.deploy-preview.environment]
    HUGO_VERSION = "0.109.0"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"

[context.branch-deploy]
command = ""

    [context.branch-deploy.environment]
    HUGO_VERSION = "0.109.0"
    NODE_VERSION = "v18.12.1"
    NPM_VERSION  = "8.19.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
